In [3]:
import numpy as np
a = np.array([20, 40, 60, 80])
print(np.append(a,90))


[20 40 60 80 90]


In [4]:
import numpy as np
a = np.array([[20, 40], [60, 80]])
print(np.append(a,90))

[20 40 60 80 90]


In [6]:
import numpy as np
a = np.array([[20, 40], [60, 80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [7]:
print(np.insert(a,1,50)) #array, index, value

[20 50 40 60 80]


In [9]:
print(np.insert(a,1,[50, 60], axis = 0))

[[20 40]
 [50 60]
 [60 80]]


In [10]:
print(np.insert(a,[1,2],[50], axis = 0))

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [14]:
print(a)
print()
print(np.delete(a,1))

[[20 40]
 [60 80]]

[20 60 80]


In [13]:
print(np.delete(a, 1, axis = 0))

[[20 40]]


In [15]:
print(np.delete(a, 1, axis = 1))

[[20]
 [60]]
