In [2]:
import numpy as np

a = [30, 40, 20, 40, 30]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))

[30 40 20 40 30]
(5,)
5


In [15]:
import numpy as np

a = [[30, 40,50],[ 20, 40, 30]]
arr = np.array(a)
print(arr)
print(arr.shape) # rows, coloums
print(len(arr)) # number of nested values
print(np.size(arr)) # number of elements
print(type(arr)) # datatype of variable
print(arr.dtype) # datatype of array
print(arr.astype(int)) # conversion of datatype

[[30 40 50]
 [20 40 30]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int32
[[30 40 50]
 [20 40 30]]
