In [2]:
import numpy as np

a = [30, 40, 20, 40, 30]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))

[30 40 20 40 30]
(5,)
5


In [13]:
import numpy as np

a = [[30, 40,50],[ 20, 40, 30]]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(int))

[[30 40 50]
 [20 40 30]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int32
