In [3]:
import numpy as np

ar = np.array([[7,8,4,12,9],[2,8,5,1,3]])
print(np.sort(ar))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [6]:
ar = np.array([3,4,1,7,8])
s = np.where(ar == 4)
print(s)

(array([1], dtype=int64),)


In [7]:
ar = np.array([3,4,1,7,8])
s = np.where(ar % 2 == 0)
print(s)

(array([1, 4], dtype=int64),)


In [9]:
ar = np.array([1, 2, 3, 4,5, 6])
ss = np.searchsorted(ar,5)
print(ss)

4


In [11]:
ar = np.array([20, 30, 40, 50])
fa = [True, False, True, False]
new = ar[fa]
print(new)

[20 40]


In [12]:
ar = np.array([20,30,40,50])
fa = ar > 35
new = ar[fa]
print(new)

[40 50]


In [16]:
ar = np.array([2,3,4,5])
fa = ar%2 ==1
new = ar[fa]
print(new)

[3 5]
