# My first Numpy Code

In [14]:
import numpy as np

a = np.array([20,30,40])
b = np.array([60,70,80])
print(a)
print(b)
print(a+b)

[20 30 40]
[60 70 80]
[ 80 100 120]


In [13]:
a = np.array([[20, 30,10], [40,50,60]])
print(a)

[[20 30 10]
 [40 50 60]]


In [15]:
l1 = [[20, 30], [40,50,60]]
print(l1)

[[20, 30], [40, 50, 60]]
